apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ssr-net-core-react-backend
  description: null
  annotations:
    github.com/project-slug: pats/SSR.NetCore.React.Backend
  tags:
    - dotnet
    - backend
spec:
  owner: null
